// @ts-nocheck
"use client";

/* eslint-disable @next/next/no-img-element */

import * as React from "react";
import { jsx, jsxs } from "react/jsx-runtime";
import { columnV15Css } from "./column-v15-styles";

const f = { jsx, jsxs };
const La = React;

type IconProps = { size?: number; strokeWidth?: number; className?: string };

function SvgIcon({ size = 24, strokeWidth = 2, className, children }: IconProps & { children: React.ReactNode }) {
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth={strokeWidth} strokeLinecap="round" strokeLinejoin="round" className={className} aria-hidden="true">{children}</svg>;
}
function Lr(p: IconProps) { return <SvgIcon {...p}><path d="M18 6 6 18M6 6l12 12" /></SvgIcon>; }
function qr(p: IconProps) { return <SvgIcon {...p}><path d="M4 6h16M4 12h16M4 18h16" /></SvgIcon>; }
function Hr(p: IconProps) { return <SvgIcon {...p}><path d="m3 11 9-8 9 8" /><path d="M5 10v10h14V10" /></SvgIcon>; }
function Co(p: IconProps) { return <SvgIcon {...p}><path d="M4 19.5V5a2 2 0 0 1 2-2h11a2 2 0 0 1 2 2v14.5" /><path d="M6 17h13M8 7h7M8 11h7" /></SvgIcon>; }
function Or(p: IconProps) { return <SvgIcon {...p}><circle cx="12" cy="8" r="4" /><path d="M4 21a8 8 0 0 1 16 0" /></SvgIcon>; }
function Ur(p: IconProps) { return <SvgIcon {...p}><circle cx="12" cy="12" r="9" /><path d="M12 7v5l3 2" /></SvgIcon>; }
function jr(p: IconProps) { return <SvgIcon {...p}><path d="m9 18 6-6-6-6" /></SvgIcon>; }
function Ar(p: IconProps) { return <SvgIcon {...p}><path d="m18 15-6-6-6 6" /></SvgIcon>; }
function vf(p: IconProps) { return <SvgIcon {...p}><path d="m12 3 1.5 4.5L18 9l-4.5 1.5L12 15l-1.5-4.5L6 9l4.5-1.5L12 3Z" /></SvgIcon>; }
function Er(p: IconProps) { return <SvgIcon {...p}><path d="m5 12 4 4L19 6" /></SvgIcon>; }
function Gr(p: IconProps) { return <SvgIcon {...p}><path d="M12 3 2.5 20h19L12 3Z" /><path d="M12 9v4M12 17h.01" /></SvgIcon>; }
function Sr(p: IconProps) { return <SvgIcon {...p}><path d="m5 12 4 4L19 6" /></SvgIcon>; }
function Kr(p: IconProps) { return <SvgIcon {...p}><circle cx="12" cy="12" r="9" /><path d="M12 8v4M12 16h.01" /></SvgIcon>; }
function _r(p: IconProps) { return <SvgIcon {...p}><path d="M4 17h16M6 17l1-7h10l1 7M8 10l2-4h4l2 4" /><circle cx="8" cy="18" r="1.5" /><circle cx="16" cy="18" r="1.5" /></SvgIcon>; }

function Header(){const[z,_]=La.useState(false);return <header className="sticky top-0 z-50 bg-white/90 backdrop-blur-sm border-b border-border-light"><div className="max-w-[1000px] mx-auto flex items-center justify-between px-4 py-3"><a href="/" className="flex items-center gap-1.5"><span className="text-xl font-bold text-text-primary font-quicksand tracking-tight">CBJ</span><span className="text-[10px] text-text-light hidden sm:inline">CAR BOUTIQUE JOURNAL</span></a><button onClick={()=>_(!z)} className="p-2 hover:bg-cream rounded-lg transition-colors" aria-label="メニュー">{z?<Lr size={22}/>:<qr size={22}/>}</button></div>{z&&<nav className="absolute top-full left-0 right-0 bg-white border-b border-border-light shadow-lg"><div className="max-w-[1000px] mx-auto py-1"><a href="/" className="flex items-center gap-3 px-6 py-3 hover:bg-cream transition-colors"><Hr size={18} className="text-juna-pink"/><span className="text-text-primary text-sm">ホーム</span></a><a href="/column" className="flex items-center gap-3 px-6 py-3 hover:bg-cream transition-colors"><Co size={18} className="text-rina-teal"/><span className="text-text-primary text-sm">レッスン</span></a><a href="/legal/about" className="flex items-center gap-3 px-6 py-3 hover:bg-cream transition-colors"><Or size={18} className="text-ch-orange"/><span className="text-text-primary text-sm">About</span></a></div></nav>}</header>}
function Hero(){return <section className="relative min-h-[85vh] flex flex-col items-center justify-center overflow-hidden" style={{background:"linear-gradient(135deg, #FF6B8A 0%, #FF8E53 100%)"}}><div className="absolute inset-0 plus-pattern opacity-40"/><div className="absolute top-[15%] left-[8%] w-16 h-16 border border-white/20 rounded-full animate-float-slow"/><div className="absolute top-[25%] right-[10%] w-10 h-10 border border-white/15 rounded-full animate-float"/><div className="absolute bottom-[20%] left-[12%] w-8 h-8 border border-white/10 rounded-full animate-float-slow" style={{animationDelay:"1s"}}/><div className="absolute top-[60%] right-[8%] w-6 h-6 bg-white/10 rounded-full animate-float" style={{animationDelay:".5s"}}/><div className="relative z-10 flex flex-col items-center px-6 text-center pt-16"><div className="flex items-center justify-center gap-4 sm:gap-6 mb-8"><div className="w-20 h-20 sm:w-24 sm:h-24 rounded-full overflow-hidden border-4 border-white/80 shadow-xl animate-float"><img src="/images/cbj/custom-regret-v15/char-juna-avatar.webp" alt="JUNA" className="w-full h-full object-cover"/></div><img src="/images/cbj/custom-regret-v15/car-illustration.webp" alt="車のイラスト" className="w-12 h-12 sm:w-14 sm:h-14 object-contain opacity-90 animate-float-slow"/><div className="w-20 h-20 sm:w-24 sm:h-24 rounded-full overflow-hidden border-4 border-white/80 shadow-xl animate-float" style={{animationDelay:"1.5s"}}><img src="/images/cbj/custom-regret-v15/char-rina-avatar.webp" alt="莉奈" className="w-full h-full object-cover"/></div></div><p className="text-white/90 text-sm tracking-[0.3em] mb-4 font-light">Lesson 17</p><h1 className="text-white text-3xl sm:text-4xl font-bold leading-tight mb-4 drop-shadow-lg">車のカスタムで<br/>後悔しやすい理由</h1><p className="text-white/80 text-sm sm:text-base max-w-md mb-8 leading-relaxed">純正を崩す前に。その変更が、車検・保証・整備入庫・売却まで、<br className="hidden sm:block"/>車全体にどう関わるかを確認する。</p><div className="flex items-center gap-3 bg-white/20 backdrop-blur-sm rounded-full px-5 py-2.5"><div className="flex items-center gap-1.5 text-white/90 text-sm"><Ur size={16}/><span>12 min read</span></div><span className="text-white/50">|</span><span className="text-white/90 text-sm">初級〜中級</span><span className="text-white/50">|</span><span className="text-white/80 text-xs">COLUMN</span></div></div><div className="absolute bottom-8 left-1/2 -translate-x-1/2 flex flex-col items-center gap-2"><span className="text-white/70 text-sm">スクロールして読む</span><div className="w-6 h-10 border-2 border-white/40 rounded-full flex justify-center pt-2"><div className="w-1.5 h-3 bg-white/60 rounded-full animate-bounce-scroll"/></div></div></section>}
function Chat({character,children}:{character:"juna"|"rina";children:React.ReactNode}){const j=character==="juna";return <div className={`flex items-start gap-3 mb-5 ${j?"flex-row-reverse":"flex-row"}`}><div className={`flex-shrink-0 w-12 h-12 sm:w-14 sm:h-14 rounded-full overflow-hidden border-[3px] shadow-md ${j?"border-juna-pink":"border-rina-teal"}`}><img src={j?"/images/cbj/custom-regret-v15/char-juna-avatar.webp":"/images/cbj/custom-regret-v15/char-rina-avatar.webp"} alt={j?"JUNA":"莉奈"} className="w-full h-full object-cover"/></div><div className={`flex flex-col ${j?"items-end":"items-start"} max-w-[78%]`}><span className={`text-[11px] font-medium mb-1.5 px-3 py-1 rounded-full ${j?"bg-juna-pink/10 text-juna-pink":"bg-rina-teal/10 text-rina-teal"}`}>{j?"JUNA（ジュナ）":"莉奈（りな）"}</span><div className={`px-5 py-4 text-[15px] leading-relaxed text-text-primary ${j?"chat-bubble-juna":"chat-bubble-rina"}`}>{children}</div></div></div>}
function InfoBox({type="point",title,children}:{type?:"point"|"check"|"caution";title?:string;children:React.ReactNode}){const map={point:{Icon:vf,color:"text-ch-orange",box:"info-box-point",label:"POINT",labelBg:"bg-ch-orange"},check:{Icon:Er,color:"text-tip-green",box:"info-box-check",label:"CHECK",labelBg:"bg-tip-green"},caution:{Icon:Gr,color:"text-trap-red",box:"info-box-caution",label:"CAUTION",labelBg:"bg-trap-red"}}[type];const Icon=map.Icon;return <div className={map.box}><div className="flex items-center gap-2 mb-3"><Icon size={20} className={map.color}/><span className={`${map.labelBg} text-white text-xs font-bold tracking-wider px-3 py-1 rounded-full`}>{map.label}</span>{title?<h4 className="font-bold text-text-primary text-sm">{title}</h4>:null}</div><div className="text-text-secondary">{children}</div></div>}
function Flow(){const items=[{num:"01",title:"カスタムは車全体で考える",color:"bg-ch-orange"},{num:"02",title:"吸気系のリスクと対策",color:"bg-ch-green"},{num:"03",title:"足回りのリスクと対策",color:"bg-ch-pink"},{num:"04",title:"電装品のリスクと対策",color:"bg-ch-blue"},{num:"05",title:"失敗しにくい進め方",color:"bg-ch-yellow"}];return <section className="bg-white rounded-2xl mx-4 p-6 shadow-card border border-border-light -mt-8 relative z-20 max-w-[800px] mx-auto mb-8"><div className="flex items-center gap-2 mb-4"><Co size={20} className="text-text-secondary"/><h2 className="text-lg font-bold text-text-primary">この記事の流れ</h2></div><div className="border-t border-dashed border-border-light pt-4 space-y-1">{items.map(x=><button key={x.num} onClick={()=>document.getElementById(`section-${x.num}`)?.scrollIntoView({behavior:"smooth"})} className="w-full flex items-center gap-4 p-3 rounded-xl hover:bg-cream transition-colors group text-left"><span className={`${x.color} text-white w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold`}>{x.num}</span><span className="flex-1 text-text-primary text-sm font-medium">{x.title}</span><jr size={18} className="text-text-light group-hover:text-text-secondary transition-colors"/></button>)}</div></section>}
function ChapterHead({number,title,subtitle,color="text-ch-orange"}:{number:string;title:string;subtitle:string;color?:string}){return <div className="relative text-center py-12 sm:py-16 px-4 overflow-hidden"><div className="absolute top-4 left-[10%] w-12 h-12 border-2 border-ch-yellow/30 rounded-full animate-float-slow"/><div className="absolute top-8 right-[15%] w-8 h-8 border-2 border-border-light rounded-full animate-float" style={{animationDelay:".5s"}}/><vf size={14} className="absolute top-6 right-[25%] text-star-gold animate-shimmer"/><vf size={12} className="absolute bottom-6 left-[20%] text-star-gold/60 animate-shimmer"/><div className={`text-7xl sm:text-8xl font-quicksand font-bold ${color} mb-2 leading-none animate-fade-in-up`}>{number}</div><h2 className="text-xl sm:text-2xl font-bold text-text-primary mb-3 leading-tight animate-fade-in-up">{title}</h2><p className="text-sm text-text-secondary max-w-sm mx-auto leading-relaxed animate-fade-in-up">{subtitle}</p></div>}
function Diagram({src,alt,caption}:{src:string;alt:string;caption:string}){return <div className="my-6"><img src={src} alt={alt} className="w-full rounded-2xl shadow-card border border-border-light"/><p className="text-xs text-text-light mt-2 text-center">{caption}</p></div>}
function Table({headers,rows}:{headers:string[];rows:string[][]}){return <div className="overflow-x-auto rounded-xl border border-border-light shadow-sm my-6"><table className="min-w-[600px]"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}
function NumberList({title,items,color="bg-tip-green"}:{title:string;items:string[];color?:string}){return <div className="bg-white rounded-2xl border border-border-light shadow-card p-5 my-6"><h4 className="font-bold text-text-primary mb-3 text-sm">{title}</h4><ul className="space-y-2.5">{items.map((x,i)=><li key={x} className="flex items-start gap-3"><div className={`${color} text-white w-5 h-5 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5`}><span className="text-white text-[10px] font-bold">{i+1}</span></div><span className="text-sm text-text-primary">{x}</span></li>)}</ul></div>}
function Intro(){return <section className="px-4 py-8 max-w-[800px] mx-auto"><Chat character="juna">どうも〜、ジュナだよ！見た目はギャルだけど車はガチ勢。カスタムで後悔したことある人、集まれ〜！</Chat><Chat character="rina">こんにちは、莉奈です。整備士の資格を持ってるんだけど、私も最初は何も知らなかったから、ジュナと一緒に勉強していこうね。</Chat><Chat character="juna">この記事ではさ、カッコよく見えるカスタムが、実は車に悪影響だったりするって話をしていくよ〜。私もエアクリ変えたら警告灯ついたことあるし…</Chat><p className="body-text mt-8 mb-4">現代の車は、エンジン・足回り・電気系統・安全装置がすべて電子的に繋がっている。一つ部品を変えると、思わぬところに影響が出ることがある。</p><p className="body-text mb-6">この記事では、吸気系・足回り・電装品の3つに焦点を当てて、「ハマりやすい罠」と「押さえるべきコツ」を解説する。</p><NumberList title="この記事でわかること" color="bg-ch-orange" items={["吸気系カスタムの熱害リスクと対策","足回り変更がADASに与える影響","CAN通信と電装品のトラブル防止","失敗しないカスタムの進め方"]}/></section>}
function Section01(){return <section id="section-01" className="py-4 scroll-mt-20"><ChapterHead number="01" title="カスタムは車全体で考える" subtitle="部品単体ではなく、センサー・ECU・保証・売却まで見る"/><div className="px-4 max-w-[800px] mx-auto"><Chat character="juna">パーツを付けるだけなのに、なんで車全体まで考えなきゃいけないの？</Chat><Chat character="rina">現代車は全部が電子制御で繋がってるから。一か所を変えると、別のセンサーや制御に影響することがあるんだよ。</Chat><h3 className="body-heading">一つの変更が複数の領域に波及する</h3><p className="body-text mb-4">エンジン、足回り、電装、安全装置は、センサーとECUを通じて連携している。吸気量、車高、電源の取り方を変えるだけでも、診断値や補正制御が純正の想定から外れることがある。</p><p className="body-text mb-4">さらに車検に通るかだけでなく、保証、整備入庫、売却時の説明、純正戻しまで含めて考える必要がある。</p><Diagram src="/images/cbj/custom-regret-v15/ch1-system-map.webp" alt="カスタムが車全体に与える影響" caption="図1：カスタムの変更が車両システム全体へ連鎖するイメージ"/><InfoBox type="point" title="物理的に付くことと、問題なく使い続けられることは別"><p>適合表、型式、年式、グレード、装備の確認に加え、取り付け後の診断や純正戻しまで計画しておく。</p></InfoBox></div></section>}
function Section02(){return <section id="section-02" className="py-4 scroll-mt-20"><ChapterHead number="02" title="吸気系のリスクと対策" subtitle="音と見た目だけで選ばず、熱・水・センサーまで確認" color="text-ch-green"/><div className="px-4 max-w-[800px] mx-auto"><Chat character="juna">吸気音を大きくしたいんだけど、剥き出しエアクリってやっぱ最高じゃない？</Chat><Chat character="rina">音は変わるけど、エンジンルームの熱い空気を吸いやすくなる。センサーの読み値や燃調も確認しないとね。</Chat><h3 className="body-heading">熱い空気を吸うと何が起きる？</h3><p className="body-text mb-4">純正吸気は外気を取り込みやすいようにダクトとボックスが設計されている。剥き出しフィルターへ変えると、停車中や渋滞時にエンジンルームの熱を吸いやすくなる。</p><p className="body-text mb-4">吸気温度が上がると空気密度が下がり、ECUは点火や燃料を補正する。構成によっては期待した性能が出ず、警告灯や不調につながる場合もある。</p><Diagram src="/images/cbj/custom-regret-v15/ch2-airflow.webp" alt="純正吸気と社外吸気の比較" caption="図2：純正吸気・剥き出しフィルター・遮熱板ありの違い"/><Table headers={["リスク","起きやすい状況","対策"]} rows={[["熱害","夏場・渋滞・停車後","遮熱板と外気導入を確保"],["水の吸い込み","雨天・洗車・低い位置","防水と取り付け位置を確認"],["センサー値の変化","径や位置が純正と違う","適合確認と診断値の記録"]]}/><InfoBox type="caution" title="音だけで選ばない"><p>製品単体の適合表示だけではなく、実車の吸気温、燃料補正、警告灯の有無まで確認する。</p></InfoBox><NumberList title="吸気系で押さえるべきコツ" items={["遮熱板と外気導入をセットで考える","雨水を直接吸わない位置と構造を選ぶ","エアフロ・吸気温・燃料補正を施工前後で確認する","純正部品と固定具をすべて保管する"]}/></div></section>}
function Section03(){return <section id="section-03" className="py-4 scroll-mt-20"><ChapterHead number="03" title="足回りのリスクと対策" subtitle="低さだけでなく、ストローク・接地・ADASまで見る" color="text-ch-pink"/><div className="px-4 max-w-[800px] mx-auto"><Chat character="juna">車高を落とすと一気にカッコよくなるよね。低ければ低いほどよくない？</Chat><Chat character="rina">見た目だけで決めると、ストローク不足や片減り、ADASのずれで後悔しやすいよ。</Chat><h3 className="body-heading">車高変更は姿勢と接地を変える</h3><p className="body-text mb-4">車高を下げるとサスペンションの残りストロークが減り、段差でバンプストップへ当たりやすくなる。アライメントも変化し、タイヤの片減りや直進性の低下につながる。</p><p className="body-text mb-4">カメラやレーダーを使うADAS搭載車では、車体姿勢の変化が認識範囲へ影響する可能性がある。変更量によってはエーミングの確認が必要になる。</p><Diagram src="/images/cbj/custom-regret-v15/ch3-suspension.webp" alt="車高変更と足回りの変化" caption="図3：ノーマル車高とローダウン時のストローク・アライメント比較"/><Table headers={["確認項目","問題が出る例","必要な対応"]} rows={[["ストローク","底付き・跳ね・接地不足","実測して必要量を確保"],["アライメント","片減り・直進性低下","施工後に測定・調整"],["ADAS","カメラ・レーダー角度の変化","必要に応じてエーミング"],["最低地上高","車検・段差・駐車場","実使用環境まで確認"]]}/><InfoBox type="caution" title="低ければ良い、硬ければ良いではない"><p>見た目、乗り心地、接地、安全装置、日常の段差を同時に成立させる範囲を決める。</p></InfoBox><NumberList title="足回りで押さえるべきコツ" color="bg-ch-pink" items={["施工前に目的と下げ幅を決める","施工後は必ずアライメントを測定する","ストロークと干渉を実車で確認する","ADAS搭載車はエーミング要否を確認する"]}/></div></section>}
function Section04(){return <section id="section-04" className="py-4 scroll-mt-20"><ChapterHead number="04" title="電装品のリスクと対策" subtitle="CAN通信と診断システムを理解してトラブルを防ぐ" color="text-ch-blue"/><div className="px-4 max-w-[800px] mx-auto"><Chat character="juna">ナビとかドラレコって、つなげば終わりじゃないの？</Chat><Chat character="rina">電装品は車の神経系統に入るから、電源・アース・CAN通信を雑に扱うと関係ない機能まで不調になるよ。</Chat><h3 className="body-heading">一つの機器が車内通信へ影響する</h3><p className="body-text mb-4">現代車では複数のECUがCAN通信を共有している。非適合機器や不適切な配線が信号へ干渉すると、警告灯や診断エラー、バッテリー上がりの原因になる。</p><Diagram src="/images/cbj/custom-regret-v15/ch4-can-network.webp" alt="CAN通信ネットワーク" caption="図4：車載CANバスネットワークの構成とECU接続図"/><Table headers={["失敗パターン","原因","症状","対策"]} rows={[["バッテリー上がり","常時電源・暗電流","数日で始動不能","ACC化・低電圧遮断"],["CANエラー","非適合機器の信号干渉","警告灯・作動不良","適合確認・正しい接続"],["アース不良","接続位置・端子処理不良","ノイズ・誤作動","専用端子と確実な圧着"],["配線損傷","無理な分岐・挟み込み","断線・ショート","保護と正規ルート施工"]]}/><InfoBox type="caution" title="OBD2機器は挿しっぱなしに注意"><p>待機電流が大きい機器は、車両停止中もバッテリーを消費する。低電圧遮断機能やACC電源化を確認する。</p></InfoBox><NumberList title="電装品カスタム前のチェックリスト" color="bg-ch-blue" items={["車種・年式・装備への適合を確認する","常時電源とACC電源を区別する","アース位置と端子処理を確認する","配線を保護し、純正ハーネスを傷めない","施工後にDTCと各機能を確認する"]}/></div></section>}
function Section05(){const steps=[{num:"01",title:"事前調査",color:"bg-ch-orange",desc:"型式・年式・グレード・装備への適合、車検、保証、影響する制御を確認する。"},{num:"02",title:"純正保管",color:"bg-ch-green",desc:"外した部品、固定具、説明書、認定書類をラベル付きで保管する。"},{num:"03",title:"施工先選定",color:"bg-ch-blue",desc:"電子制御やADASを理解する認証工場・専門店へ依頼する。"},{num:"04",title:"データ記録",color:"bg-check-purple",desc:"施工前後の警告灯、DTC、診断値、アライメント、写真を残す。"},{num:"05",title:"定期確認",color:"bg-text-secondary",desc:"施工直後だけでなく、1週間・1か月・季節変化後にも異常を確認する。"}];return <section id="section-05" className="py-4 scroll-mt-20"><ChapterHead number="05" title="失敗しにくい進め方" subtitle="正しい順番と確認ポイントで安心カスタム" color="text-ch-yellow"/><div className="px-4 max-w-[800px] mx-auto"><Chat character="juna">色々聞いたけど、結局どう進めれば失敗しないの？</Chat><Chat character="rina">やる前の準備、施工後の確認、戻せる状態。この3つを崩さないことだね。</Chat><Diagram src="/images/cbj/custom-regret-v15/ch5-steps.webp" alt="安全なカスタム5ステップ" caption="図5：安全なカスタム進行の5ステップフロー"/><h3 className="body-heading">安全なカスタム進行の5ステップ</h3><div className="space-y-4 my-6">{steps.map(s=><div key={s.num} className="flex gap-3 bg-white rounded-xl border border-border-light p-4 shadow-card"><div className={`${s.color} text-white w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 text-sm font-bold`}>{s.num}</div><div><h5 className="font-bold text-text-primary text-sm">{s.title}</h5><p className="text-xs text-text-secondary leading-relaxed mt-0.5">{s.desc}</p></div></div>)}</div><InfoBox type="point" title="施工前後を比較できる状態にする"><p>警告灯の有無だけでなく、DTC、燃料補正、吸気温、アライメントなど、変更箇所に関係する値を記録する。</p></InfoBox><InfoBox type="check" title="保証とカスタムを両立させる"><ul className="space-y-1.5"><li>・購入前にディーラーや施工店へ相談する</li><li>・認証品・適合品でも取り付け状態を確認する</li><li>・部品保証と施工保証の範囲を残す</li><li>・純正へ戻す費用と手順を把握する</li></ul></InfoBox><NumberList title="カスタム前の最終チェック" color="bg-ch-orange" items={["自分の車両型式・年式・装備に適合している","車検・保証・整備入庫への影響を確認した","純正部品と書類を保管できる","施工後の診断・調整まで依頼できる","売却時に変更内容を説明し、戻せる"]}/></div></section>}
function Outro(){return <section className="px-4 py-8 max-w-[800px] mx-auto"><Chat character="juna">全部に共通するのは「調べてからやる」と「純正を残す」ことだね。</Chat><Chat character="rina">そう。正しい情報を持って、専門家と相談しながら進めれば、カスタムはちゃんと楽しめるよ。</Chat><Chat character="juna">安さや見た目だけで決めず、時間とお金をかけて計画する。これが後悔しないコツ！</Chat><InfoBox type="point">カスタムは「付ける」だけではなく、「車全体にどう影響するか」「あとで戻せるか」まで考える。</InfoBox><p className="body-text mt-6">安全性、診断性、保証、整備、売却まで含めて、自分の使い方に合う範囲で楽しもう。</p></section>}
function Footer(){return <footer className="relative py-8"><button onClick={()=>window.scrollTo({top:0,behavior:"smooth"})} className="fixed bottom-6 right-6 w-12 h-12 bg-ch-orange rounded-full shadow-lg flex items-center justify-center hover:scale-110 transition-transform z-40" aria-label="ページ上部へ戻る"><Ar size={24} className="text-white"/></button><div className="h-20"/></footer>}

export function ColumnV15ArticlePage() {
  return <><style dangerouslySetInnerHTML={{ __html: columnV15Css }} /><div className="cbj-v15-page min-h-screen bg-cream"><Header/><main className="pb-8"><Hero/><Intro/><Flow/><Section01/><Section02/><Section03/><Section04/><Section05/><Outro/></main><Footer/></div></>;
}
