// @ts-nocheck
"use client";

/* eslint-disable @next/next/no-img-element */

import { f } from "./column-v15-icons";
import { Au, k, $t, yf } from "./column-v15-core";

function Ir(){return f.jsxs("section",{id:"section-01",className:"py-4 scroll-mt-20",children:[f.jsx(Au,{number:"01",title:"カスタムは車「全体」で考える",subtitle:"部品単体じゃなく、センサー・保証・売却まで視野に入れよう",color:"text-ch-orange"}),f.jsxs("div",{className:"px-4 max-w-[800px] mx-auto",children:[f.jsx(k,{character:"shuna",children:"カスタムって、「このホイールかっこいい」とか「このマフラー音いいよね」ってパーツ単体で選びがちじゃん？"}),f.jsx(k,{character:"rina",children:"そうだね、見た目で選んじゃうのはわかるよ。でも一つ変えると、意外なところまで影響することがあるんだよね。"}),f.jsx(k,{character:"shuna",children:"エアクリを変えるだけでも、警告灯がつくことってあるの？"}),f.jsx(k,{character:"rina",children:"あ〜、あるある！エアフローセンサーが変な数値出しちゃうパターンだね。"}),f.jsx("h3",{className:"body-heading",children:"なぜ部品単体で考えると失敗するのか"}),f.jsx("p",{className:"body-text mb-4",children:"現代の車はCAN（Controller Area Network）通信により、数十個のECU（電子制御ユニット）がリアルタイムでデータを交換している。"}),f.jsx("p",{className:"body-text mb-4",children:"吸気系の変更はエアフローセンサーの信号値を変え、それが燃料噴射量・点火時期・排ガス制御に連鎖的に影響する。単一パーツの視点では捕捉できない、システム全体の相互作用を常に意識する必要がある。"}),f.jsx("p",{className:"body-text mb-4",children:"エアフローセンサー（MAF）は吸入空気量をECUに伝える重要なセンサーだ。"}),f.jsx("p",{className:"body-text mb-4",children:"フィルター形状や口径を変えると、センサーが検出する流速分布が変わり、ECUは誤った空気量を認識してしまうことがある。"}),f.jsxs("div",{className:"my-6",children:[f.jsx("img",{src:"/images/cbj/custom-regret-v15/ch1-system-map.avif",alt:"カスタムによる車両システムへの影響関係図",className:"w-full rounded-2xl shadow-card border border-border-light"}),f.jsx("p",{className:"text-xs text-text-light mt-2 text-center",children:"図1：カスタムパーツと車両システムの影響関係マップ"})]}),f.jsx(k,{character:"shuna",children:"わかりやすい！つまり全部繋がってるんだね。"}),f.jsx(k,{character:"rina",children:"その通り。次の表で3つの要素をまとめるね。"}),f.jsxs("div",{className:"space-y-4 my-6",children:[f.jsxs(yf,{number:"01",title:"吸気系",color:"bg-ch-orange",barColor:"bg-orange-400",children:[f.jsx("p",{children:"エアフローセンサー・燃料噴射量・点火時期・排ガス制御に直結。"}),f.jsx("p",{children:"エンジンルーム温度の変化はECUの学習値に影響する。"})]}),f.jsxs(yf,{number:"02",title:"足回り",color:"bg-ch-pink",barColor:"bg-pink-400",children:[f.jsx("p",{children:"車高変更はアライメント・センサー照準・安全装置（ADAS）に波及。"}),f.jsx("p",{children:"ミリ波レーダー・カメラの光軸ずれは最悪の場合作動不良を招く。"})]}),f.jsxs(yf,{number:"03",title:"電装品",color:"bg-ch-blue",barColor:"bg-blue-400",children:[f.jsx("p",{children:"CAN通信バスへの接続はECU間通信の信頼性に関わる。"}),f.jsx("p",{children:"未認証機器の接続でバス負荷上昇・エラー検出の可能性がある。"})]})]}),f.jsx($t,{type:"point",children:"カスタムは「付ける」だけじゃなくて、「車全体にどう影響するか」を考えることが大事！"}),f.jsx($t,{type:"caution",title:"ECUの自己学習機能",children:"現代のECUは自己学習機能（Adaptive Learning）を持ち、短時間・長時間の2つの学習値を記憶している。カスタム後に元に戻しても、学習値は即座にリセットされません。ディーラーでの学習値クリア（Initialization）が必要な場合があり、費用は3,000〜15,000円程度です。"})]})]})}
function gf({headers:z,rows:_}){return f.jsx("div",{className:"overflow-x-auto my-5 rounded-2xl bg-white border border-border-light",children:f.jsxs("table",{className:"w-full text-sm",children:[f.jsx("thead",{children:f.jsx("tr",{className:"bg-gray-50",children:z.map((D,h)=>f.jsx("th",{className:"px-4 py-3 text-left font-bold text-xs text-text-primary tracking-wider border-b border-border-light",children:D},h))})}),f.jsx("tbody",{children:_.map((D,h)=>f.jsx("tr",{className:h%2===0?"bg-white":"bg-gray-50/50",children:D.map((H,Y)=>f.jsx("td",{className:"px-4 py-3 text-text-secondary text-[13px] leading-relaxed border-b border-border-light/60",children:H},Y))},h))})]})})}
function Pr(){return f.jsxs("section",{id:"section-02",className:"py-4 scroll-mt-20",children:[f.jsx(Au,{number:"02",title:"吸気系のリスクと対策",subtitle:"音カッコいいのは正義だけど、熱害でパワー落ちるのは本末転倒",color:"text-ch-green"}),f.jsxs("div",{className:"px-4 max-w-[800px] mx-auto",children:[f.jsx(k,{character:"shuna",children:"「エンジン音をカッコよくしたい！」って、剥き出しのエアクリを選ぶ人もいるの？"}),f.jsx(k,{character:"rina",children:"あるよ。オープンタイプのエアクリは音は良くなるけど、熱の問題があるよね。"}),f.jsx(k,{character:"shuna",children:"夏場の渋滞でパワーが落ちたり、警告灯がついたりするの？"}),f.jsx(k,{character:"rina",children:"あ〜、あれね。熱害ってやつ。エンジンルームの熱風を吸い込んじゃうんだよね。"}),f.jsx(k,{character:"shuna",children:"雨水が入る心配もあるんだ。もし合わなかったら、純正に戻せるようにしておくのが大事なんだね。"}),f.jsx("h3",{className:"body-heading",children:"剥き出しエアクリの仕組みと問題点"}),f.jsx("p",{className:"body-text mb-4",children:"純正のエアクリーナーは、フロントグリルやフェンダーから外気を取り入れる「ダクト」がついている。これにより、エンジンルームの熱を避けて比較的低い温度の空気を供給できる。"}),f.jsx("p",{className:"body-text mb-4",children:"一方、社外の「剥き出し（オープン）エアクリ」はフィルター部分がむき出しになっている。見た目はカッコいいし、エンジン音も良く聞こえる。"}),f.jsx("h3",{className:"body-heading text-ch-orange",children:"しかし3つの大きな問題がある："}),f.jsx("h4",{className:"text-base font-bold text-ch-orange mt-6 mb-3",children:"① 熱害（ねつがい）"}),f.jsx("p",{className:"body-text mb-4",children:"エンジンルーム内は走行中でも60〜80℃、渋滞時は100℃近くなる。"}),f.jsx("p",{className:"body-text mb-4",children:"高温の空気は密度が低く、同じ体積でも酸素の量が少ない。ECUは吸気温度センサーの情報をもとに燃料噴射量を調整するが、想定外の高温になると「混合気が薄い」と誤認識したり、過度に濃く調整したりして、パワーダウンや燃費悪化の原因になる。"}),f.jsx("h4",{className:"text-base font-bold text-ch-orange mt-6 mb-3",children:"② センサー読み値の変化"}),f.jsx("p",{className:"body-text mb-4",children:"純正エアクリにはエアフローセンサー（MAF）が最適な位置に配置されている。"}),f.jsx("p",{className:"body-text mb-4",children:"社外品に変えると、センサーの前後の気流が乱れて正確な計測ができなくなる。特にマスエアフロータイプのセンサーは気流の向きや速度に敏感で、10%以上の読み違いが起きることも。"}),f.jsx("h4",{className:"text-base font-bold text-ch-orange mt-6 mb-3",children:"③ 雨水の浸入"}),f.jsx("p",{className:"body-text mb-4",children:"純正ダクトは雨水の浸入を防ぐ構造になっているが、剥き出しタイプはエンジンルーム内に設置されるため、雨天時や洗車時に水滴が飛散してフィルターに付着するリスクがある。"}),f.jsx("p",{className:"body-text mb-4",children:"水を吸い込むと「水槌現象」でエンジン内部を損傷する恐れがある。"}),f.jsxs("div",{className:"my-6",children:[f.jsx("img",{src:"/images/cbj/custom-regret-v15/ch2-airflow.avif",alt:"エアインテーク熱害メカニズム図解",className:"w-full rounded-2xl shadow-card border border-border-light"}),f.jsx("p",{className:"text-xs text-text-light mt-2 text-center",children:"図2：エアインテーク系の熱害メカニズムと遮熱板の効果"})]}),f.jsx("h3",{className:"body-heading",children:"よくある失敗パターン"}),f.jsx(gf,{headers:["失敗パターン","原因","症状","対策"],rows:[["夏場の渋滞でパワー落ち","熱害（高温空気吸入）","遮熱板付きキットを選ぶ"],["警告灯が点灯","MAFセンサー読み違い","センサー位置を調整/純正に戻す"],["車検で指摘","EVAP配管干渉","配管の干渉確認/純正戻し"],["エンジン不調","雨水吸入・フィルター劣化","防水対策/定期交換"]]}),f.jsx($t,{type:"check",title:"純正品は絶対に保管する",children:"車検や売却、ディーラー入庫の時に純正品に戻せるように、ダンボール箱に入れて湿気のない場所に保管しておこう。"}),f.jsx($t,{type:"caution",title:"安いノーブランドエアクリの危険性",children:"「安いから」という理由でノーブランドのエアクリを選ぶと、フィルターの目が粗くてホコリを通しやすく、エンジンへのダメージが累積するリスクがある。信頼できるメーカーの製品を選ぼう。"})]})]})}

export { Ir, gf, Pr };
