import { Fragment } from "react";
import Image from "next/image";
import Link from "next/link";

import { TextWithInternalLinkCards } from "@/components/content/TextWithInternalLinkCards";
import { renderInlineMarkdown } from "@/components/content/InlineMarkdown";
import type { InternalLinkMeta } from "@/lib/content/internal-link-index";
import type { GuideDetailSection } from "@/lib/content-types";
import type { EditorialArticleLabels, EditorialArticlePageProps, EditorialArticleViewModel } from "@/components/editorialArticle/EditorialArticlePage";
import customRegretLayoutJson from "@/data/article-layouts/modern-car-custom-regret-reason-column.layout.json";

import styles from "@/components/editorialArticle/kinto-json-article.module.css";

type ArticleSection = GuideDetailSection & { id: string; displayTitle: string; label: string };
type Block = Record<string, any>;
type KintoArticle = EditorialArticleViewModel & { slug?: string | null; layoutId?: string | null };
type KintoArticleProps = Omit<EditorialArticlePageProps, "article"> & { article: KintoArticle };
type LayoutConfig = {
  slug: string;
  designSystem?: string;
  classNames?: Record<string, string>;
  hero?: { imageSrc?: string; imageAlt?: string; characterSrc?: string; characterAlt?: string; badge?: string; score?: string; guideLabel?: string };
  imageOverrides?: Record<string, string>;
  sections?: Record<string, { className?: string; chapterClassName?: string; bodyClassName?: string; characterSrc?: string }>;
};

const customRegretLayout = customRegretLayoutJson as LayoutConfig;
const styleMap = styles as Record<string, string>;
const stripNumber = (text?: string | null) => String(text ?? "").replace(/^\s*(?:第?\d{1,2}(?:章|話|部|項)|[①②③④⑤⑥⑦⑧⑨⑩])\s*[\).）．.、:：-]?\s*/u, "").replace(/^\s*\d{1,2}\s*[\).）．.、:：-]?\s*/u, "").trim();
const compact = (text?: string | null) => String(text ?? "").replace(/\s+/g, "").trim();
const idFrom = (text: string, index: number) => text.trim().toLowerCase().replace(/[^a-z0-9\u3040-\u30ff\u4e00-\u9faf]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 60) || `section-${index + 1}`;
const css = (key?: string | null) => (key ? styleMap[key] ?? "" : "");
const cx = (...classes: Array<string | false | null | undefined>) => classes.filter(Boolean).join(" ");
const cls = (layout: LayoutConfig | null, key: string) => css(layout?.classNames?.[key]);

function layoutFor(article: KintoArticle): LayoutConfig | null {
  return article.slug === customRegretLayout.slug || article.layoutId === customRegretLayout.slug || article.layoutId === customRegretLayout.designSystem ? customRegretLayout : null;
}
function dateDot(iso?: string | null): string { if (!iso) return ""; const d = new Date(iso); if (Number.isNaN(d.getTime())) return ""; return `${d.getFullYear()}.${String(d.getMonth() + 1).padStart(2, "0")}.${String(d.getDate()).padStart(2, "0")}`; }
function labelFor(title: string, index: number, labels: EditorialArticleLabels): string { const text = compact(title); if (/まとめ|SUMMARY/.test(text)) return "SUMMARY"; if (/中古/.test(text)) return "USED CAR"; if (/戻せない|負担|RISK/.test(text)) return "RISK"; if (/車検|LEGAL|保安/.test(text)) return "LEGAL"; if (/進め方|FLOW|順番/.test(text)) return "FLOW"; if (/選び方|PARTS|カスタム別/.test(text)) return "PARTS"; return labels.footerListHref.startsWith("/column") ? (index === 0 ? "BASICS" : "VIEW") : (index === 0 ? "BASICS" : "GUIDE"); }
function normalizeSections(article: KintoArticle, labels: EditorialArticleLabels): ArticleSection[] { return (article.sections ?? []).map((section, index) => { const title = stripNumber(section.title) || `セクション${index + 1}`; return { ...section, id: section.id?.trim() || idFrom(title, index), displayTitle: section.displayTitle?.trim() || title, label: section.chapterLabel?.trim() || labelFor(title, index, labels) }; }); }
function RichText({ text, linkIndex, as = "p", className, highlights }: { text: string; linkIndex: Record<string, InternalLinkMeta>; as?: "p" | "span"; className?: string; highlights?: string[] | null }) { return <TextWithInternalLinkCards text={text} linkIndex={linkIndex} as={as} className={styles.richText} textClassName={className ?? styles.paragraph} cardsClassName={styles.inlineCards} highlights={highlights ?? undefined} />; }
function mainTitle(title: string) { return stripNumber(title.split(/。\n|\n/u)[0]).replace(/。$/u, "") || title; }
function subTitle(title: string) { return title.split(/。\n|\n/u).slice(1).join("。 ").replace(/。$/u, "").trim(); }
function importantLine(article: KintoArticle) { for (const section of article.sections ?? []) for (const block of ((section.blocks ?? []) as Block[])) { const hit = Array.isArray(block.highlights) ? block.highlights.find((item: string) => /物理的|使い続け|戻せない|説明/.test(item)) : null; if (hit) return hit; } return article.keyPoints?.[0] ?? article.checkpoints?.[0] ?? null; }

function Hero({ article, labels, layout }: { article: KintoArticle; labels: EditorialArticleLabels; layout: LayoutConfig | null }) {
  const updated = dateDot(article.updatedAt || article.publishedAt);
  const title = mainTitle(article.title);
  const score = layout?.hero?.score ?? "10/10";
  return <header className={cx(styles.hero, cls(layout, "hero"))}><div className={styles.container}><div className={styles.saveRow}><span>{layout?.hero?.badge ?? "保存版"}</span><i /></div><div className={styles.heroLayout}><div className={styles.heroCopy}><p className={styles.category}>{labels.footerListHref.startsWith("/column") ? "COLUMN" : "GUIDE"}</p><h1>{title.includes("後悔") ? <>{title.replace(/後悔しやすい理由/u, "")}<strong>後悔しやすい理由</strong></> : title}</h1><p className={styles.heroLead}>{subTitle(article.title) || article.lead}</p><dl className={styles.heroMeta}>{updated ? <div><dt>UPDATED</dt><dd>{updated}</dd></div> : null}{article.readMinutes ? <div><dt>READ</dt><dd>{article.readMinutes} MIN</dd></div> : null}</dl></div><div className={styles.guideArea} aria-hidden="true"><div className={styles.scoreCircle}><b>{score.split("/")[0]}</b><span>/{score.split("/")[1] ?? "10"}</span></div>{layout?.hero?.characterSrc ? <Image className={styles.guideCharacterImage} src={layout.hero.characterSrc} alt={layout.hero.characterAlt || ""} width={240} height={360} priority /> : null}</div></div></div></header>;
}
function Intro({ article, linkIndex, layout }: { article: KintoArticle; linkIndex: Record<string, InternalLinkMeta>; layout: LayoutConfig | null }) { const line = importantLine(article); const heroImage = layout?.hero?.imageSrc ?? article.heroImage; return <section className={cx(styles.introBand, cls(layout, "intro"))}><div className={styles.containerSm}>{article.lead ? <RichText text={article.lead} linkIndex={linkIndex} className={cx(styles.introText, cls(layout, "leadParagraph"))} /> : null}{heroImage ? <figure className={styles.heroImage}><Image src={heroImage} alt={layout?.hero?.imageAlt || article.heroAlt || article.title} width={1600} height={1000} sizes="(max-width: 760px) 100vw, 820px" priority /></figure> : null}{line ? <aside className={cx(styles.importantBox, cls(layout, "important"))}><span>重要</span><p>{line}</p></aside> : null}</div></section>; }
function renderImage(block: Block, key: string, layout: LayoutConfig | null) { const src = layout?.imageOverrides?.[block.src] ?? block.src; if (!src) return null; return <figure key={key} className={cx(styles.figure, cls(layout, "figure"))} data-fit={block.fit ?? "cover"}><Image src={src} alt={block.alt || ""} width={1600} height={1000} sizes="(max-width: 760px) 100vw, 760px" />{(block.label || block.alt) ? <figcaption>{block.label || block.alt}</figcaption> : null}</figure>; }
function renderList(items: string[] = [], key: string, linkIndex: Record<string, InternalLinkMeta>, layout: LayoutConfig | null) { return <ol key={key} className={cx(styles.stepList, cls(layout, "list"))}>{items.map((item, index) => <li key={index}><span>{String(index + 1).padStart(2, "0")}</span><RichText text={item} linkIndex={linkIndex} as="span" className={cx(styles.smallText, cls(layout, "paragraph"))} /></li>)}</ol>; }
function renderTable(block: Block, key: string, linkIndex: Record<string, InternalLinkMeta>, layout: LayoutConfig | null) { const headers = Array.isArray(block.headers) ? block.headers.slice(1) : []; const ngOk = headers.some((header: string) => /NG|避けたい/.test(header)) || headers.some((header: string) => /OK|確認/.test(header)); return <section key={key} className={cx(ngOk ? styles.ngOkBlock : styles.checkBlock, cls(layout, ngOk ? "ngOk" : "checkCards"))}>{block.title ? <h3>{renderInlineMarkdown(stripNumber(block.title))}</h3> : null}<div>{(block.rows ?? []).map((row: string[], rowIndex: number) => { const title = stripNumber(row[0] ?? `${rowIndex + 1}`); const values = row.slice(1); return ngOk ? <article key={rowIndex} className={styles.ngOkCard}><h4>{title}</h4><div>{values.map((value, valueIndex) => <section key={valueIndex} className={cx(valueIndex === 0 ? styles.ngPane : styles.okPane, cls(layout, valueIndex === 0 ? "ngPane" : "okPane"))}><b>{valueIndex === 0 ? "NG" : "OK"}</b><RichText text={value} linkIndex={linkIndex} className={cx(styles.smallText, cls(layout, "paragraph"))} /></section>)}</div></article> : <article key={rowIndex} className={cx(styles.checkCard, cls(layout, "checkCard"))}><span>{String(rowIndex + 1).padStart(2, "0")}</span><div><h4>{title}</h4><RichText text={values[0] ?? ""} linkIndex={linkIndex} className={cx(styles.smallText, cls(layout, "paragraph"))} /></div></article>; })}</div>{block.note ? <p className={styles.note}>{renderInlineMarkdown(block.note)}</p> : null}</section>; }
function renderFlow(block: Block, key: string, layout: LayoutConfig | null) { const steps = block.steps ?? block.items ?? []; return <section key={key} className={cx(styles.flowBlock, cls(layout, "flow"))}>{block.title ? <h3>{renderInlineMarkdown(stripNumber(block.title))}</h3> : null}<ol>{steps.map((step: Block, index: number) => <li key={index}><span>{step.label || String(index + 1).padStart(2, "0")}</span><div>{step.title ? <h4>{renderInlineMarkdown(stripNumber(step.title))}</h4> : null}{step.body ? <p>{renderInlineMarkdown(step.body)}</p> : null}</div></li>)}</ol></section>; }
function renderCards(block: Block, key: string, linkIndex: Record<string, InternalLinkMeta>, layout: LayoutConfig | null) { const items = block.cards ?? block.items ?? block.cases ?? []; return <section key={key} className={cx(styles.cardsBlock, cls(layout, "cards"))}>{block.title ? <h3>{renderInlineMarkdown(stripNumber(block.title))}</h3> : null}<div>{items.map((item: Block, index: number) => <article key={index} className={cx(styles.infoCard, cls(layout, "card"))}><span>{item.badge ?? item.number ?? String(index + 1).padStart(2, "0")}</span><b>{renderInlineMarkdown(stripNumber(item.title))}</b>{item.body || item.intro ? <RichText text={item.body ?? item.intro} linkIndex={linkIndex} className={cx(styles.cardText, cls(layout, "paragraph"))} /> : null}{item.items?.length ? renderList(item.items, `${key}-${index}`, linkIndex, layout) : null}</article>)}</div></section>; }
function renderCallout(block: Block, key: string, linkIndex: Record<string, InternalLinkMeta>, layout: LayoutConfig | null) { const warn = block.tone === "warn"; return <aside key={key} className={cx(warn ? styles.warnCard : styles.infoCard, cls(layout, warn ? "calloutWarn" : "calloutInfo"))}>{block.title ? <b>{renderInlineMarkdown(stripNumber(block.title))}</b> : null}{block.body ? <RichText text={block.body} linkIndex={linkIndex} className={cx(styles.cardText, cls(layout, "paragraph"))} /> : null}{block.items?.length ? renderList(block.items, `${key}-items`, linkIndex, layout) : null}</aside>; }
function renderBlock(block: Block, index: number, linkIndex: Record<string, InternalLinkMeta>, layout: LayoutConfig | null) { const key = `block-${index}`; switch (block.type) { case "paragraph": return <RichText key={key} text={block.text} linkIndex={linkIndex} className={cx(index === 0 ? styles.leadParagraph : styles.paragraph, cls(layout, index === 0 ? "leadParagraph" : "paragraph"))} highlights={block.highlights} />; case "image": return renderImage(block, key, layout); case "list": return renderList(block.items, key, linkIndex, layout); case "subheading": return <h3 key={key} className={cx(styles.subheading, cls(layout, "subheading"))}>{renderInlineMarkdown(stripNumber(block.title))}</h3>; case "quote": return <blockquote key={key} className={cx(styles.quote, cls(layout, "quote"))}>{renderInlineMarkdown(block.text)}</blockquote>; case "divider": return <hr key={key} className={styles.divider} />; case "comparisonTable": return renderTable(block, key, linkIndex, layout); case "callout": return renderCallout(block, key, linkIndex, layout); case "flow": case "timeline": return renderFlow(block, key, layout); case "decisionCards": case "editorialBoard": case "caseStudy": return renderCards(block, key, linkIndex, layout); default: return null; } }
function sectionClass(section: ArticleSection, index: number, layout: LayoutConfig | null) { const sectionLayout = layout?.sections?.[section.id]; const text = compact(`${section.label} ${section.title}`); return cx(styles.section, index % 2 === 0 ? styles.whiteSection : styles.softSection, /戻せない|負担|RISK/.test(text) ? styles.darkSection : "", css(sectionLayout?.className)); }
export function KintoJsonArticlePage({ article, labels, linkIndex }: KintoArticleProps) { const layout = layoutFor(article); const sections = normalizeSections(article, labels); const faq = article.faq ?? []; const sources = (article.sources ?? []).filter(Boolean); const related = article.relatedItems ?? []; return <main className={cx(styles.page, cls(layout, "page"))} data-cbj-article-page><Hero article={article} labels={labels} layout={layout} /><Intro article={article} linkIndex={linkIndex} layout={layout} />{sections.map((section, index) => { const sectionLayout = layout?.sections?.[section.id]; return <section key={section.id} id={section.id} className={sectionClass(section, index, layout)}><div className={styles.container}><div className={cx(styles.chapterHead, css(sectionLayout?.chapterClassName))}><div><p>CHAPTER {String(index + 1).padStart(2, "0")}</p><h2>{section.displayTitle}</h2>{section.deck ? <span>{section.deck}</span> : null}</div>{sectionLayout?.characterSrc ? <Image className={styles.chapterCharacter} src={sectionLayout.characterSrc} alt="" width={120} height={180} /> : null}</div><div className={cx(styles.bodyFlow, css(sectionLayout?.bodyClassName))}>{(section.blocks as Block[]).map((block, blockIndex) => <Fragment key={`${section.id}-${blockIndex}`}>{renderBlock(block, blockIndex, linkIndex, layout)}</Fragment>)}</div></div></section>; })}{faq.length ? <section className={cx(styles.faqSection, cls(layout, "faq"))} id="faq"><div className={styles.container}><p>FAQ ／ よくある質問</p><h2>よくある質問</h2><div>{faq.map((item, index) => <details key={index}><summary><b>Q</b>{item.question}<i>＋</i></summary><p>{item.answer}</p></details>)}</div></div></section> : null}{(sources.length || article.updateText) ? <section className={styles.sourceSection}><div className={styles.container}>{sources.length ? <details><summary>{labels.sourcesTitle ?? "出典・参考資料"}<span>{sources.length}件</span></summary><ol>{sources.map((source, index) => <li key={index}>{source}</li>)}</ol></details> : null}{article.updateText ? <details><summary>{labels.updateTitle ?? "更新履歴"}<span>表示</span></summary><p>{article.updateText}</p></details> : null}</div></section> : null}{related.length ? <section className={cx(styles.relatedSection, cls(layout, "related"))}><div className={styles.container}><p>RELATED</p><h2>{labels.relatedTitle}</h2><div>{related.slice(0, 3).map((item) => <Link key={item.href} href={item.href}>{item.imageSrc ? <Image src={item.imageSrc} alt={item.imageAlt || item.title} width={640} height={400} /> : null}<small>{item.metaLabel}</small><b>{item.title}</b><span>{item.summary}</span></Link>)}</div></div></section> : null}</main>; }
